# https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2

updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "07:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: increase
    commit-message:
      include: "scope"
      prefix: "composer"
#    ignore:
#      - dependency-name: infection/infection
#        versions:
#          - ">= 0"
#      - dependency-name: phpunit/phpunit
#        versions:
#          - ">= 0"
#      - dependency-name: symfony/finder
#        versions:
#          - ">= 0"
#      - dependency-name: laminas/laminas-diactoros
#        versions:
#          - ">= 0"

  - package-ecosystem: "composer"
    directory: "vendor-bin/phpcs/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: increase
    commit-message:
      include: "scope"
      prefix: "composer"

  - package-ecosystem: "composer"
    directory: "vendor-bin/phpstan/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: increase
    commit-message:
      include: "scope"
      prefix: "composer"

  - package-ecosystem: "composer"
    directory: "vendor-bin/phpunit/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: increase
    commit-message:
      include: "scope"
      prefix: "composer"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "07:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    commit-message:
      include: "scope"
      prefix: "github-actions"
