language: php
sudo: false

php:
  - 7.0
  - 7.1
  - nightly

os:
  - linux

env:
  - COMPOSER_FLAGS="--prefer-lowest"
  - COMPOSER_FLAGS=""

matrix:
  include:
    - php: 7.1
      env: COVERAGE=yes
      sudo: required
      dist: trusty
      group: edge
    - php: 7.1
      env: EXECUTE_CS_CHECK=yes
    - php: nightly
      env: COMPOSER_FLAGS="--ignore-platform-reqs"
  allow_failures:
    - php: nightly

cache:
  directories:
    - $HOME/.composer/cache

addons:
  code_climate:
    repo_token: 43db4d76514521ffd97e65f2a6806a106ae168f1db55397741485212f9c70ae7

before_install:
  - if [[ $TRAVIS_PHP_VERSION != nightly && $COVERAGE != yes ]]; then phpenv config-rm xdebug.ini; fi
  - echo 'opcache.enable=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo 'opcache.enable_cli=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - travis_retry composer self-update

install:
  - travis_retry composer update --optimize-autoloader --prefer-dist --prefer-stable --no-progress --no-interaction $COMPOSER_FLAGS

script:
  - composer validate
  - if [[ $COVERAGE == yes ]]; then vendor/bin/phpunit --coverage-clover=clover.xml; else vendor/bin/phpunit --no-coverage; fi
  - if [[ $EXECUTE_CS_CHECK == yes ]]; then php -n -d memory_limit=768M vendor/bin/phpcs; fi
  - if [[ $EXECUTE_CS_CHECK == yes ]]; then php -n -d memory_limit=768M vendor/bin/php-cs-fixer fix --dry-run -vv; fi

after_success:
  - if [[ $COVERAGE == yes ]]; then wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar && php -n coveralls.phar --verbose --coverage_clover=clover.xml; fi
  - if [[ $COVERAGE == yes ]]; then bash <(curl -s https://codecov.io/bash); fi

notifications:
  email: false
