language: php
sudo: false
dist: trusty

php:
  - 7.1
  - 7.2

os: linux

env:
  - COMPOSER_FLAGS="--prefer-lowest"
  - COMPOSER_FLAGS=""

cache:
  directories:
    - $HOME/.composer/cache

addons:
  code_climate:
    repo_token: 43db4d76514521ffd97e65f2a6806a106ae168f1db55397741485212f9c70ae7

before_install:
  - phpenv config-rm xdebug.ini || echo "xdebug not available"
  - echo 'opcache.enable=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo 'opcache.enable_cli=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - travis_retry composer self-update

install:
  - travis_retry composer update --optimize-autoloader --prefer-dist --prefer-stable --no-progress --no-interaction --no-suggest --no-dev $COMPOSER_FLAGS -vv
  - travis_retry composer require --update-with-dependencies --prefer-dist --prefer-stable --no-progress --no-interaction --no-suggest phpunit/phpunit:^6.2
  - travis_retry composer require --update-with-dependencies --prefer-dist --prefer-stable --no-progress --no-interaction --no-suggest scriptfusion/phpunit-immediate-exception-printer:^1.0

script:
  - composer validate
  - vendor/bin/phpunit --printer 'ScriptFUSION\PHPUnitImmediateExceptionPrinter\ImmediateExceptionPrinter' --colors --no-coverage

jobs:
  allow_failures:
    - php: nightly
  include:
    - php: nightly
      env: COMPOSER_FLAGS="--ignore-platform-reqs"
    - stage: test with coverage
      php: 7.1
      env:
        - COVERAGE=yes
        - COMPOSER_FLAGS=""
      before_install:
        - echo 'opcache.enable=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
        - echo 'opcache.enable_cli=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
        - travis_retry composer self-update
      script: vendor/bin/phpunit --printer 'ScriptFUSION\PHPUnitImmediateExceptionPrinter\ImmediateExceptionPrinter' --colors --coverage-clover=clover.xml --coverage-text
      after_success:
        - wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar && php -n coveralls.phar --verbose --coverage_clover=clover.xml
        - bash <(curl -s https://codecov.io/bash) -f clover.xml -F phpunit
    - stage: check coding style
      php: 7.1
      env: COMPOSER_FLAGS=""
      install:
        - travis_retry composer update --optimize-autoloader --prefer-dist --prefer-stable --no-progress --no-interaction --no-suggest --no-dev $COMPOSER_FLAGS -vv
        - travis_retry composer require --update-with-dependencies --prefer-dist --prefer-stable --no-progress --no-interaction --no-suggest squizlabs/php_codesniffer:^3.0
      script: vendor/bin/phpcs --colors
    - stage: check coding style
      php: 7.1
      env: COMPOSER_FLAGS=""
      install:
        - travis_retry composer update --optimize-autoloader --prefer-dist --prefer-stable --no-progress --no-interaction --no-suggest --no-dev $COMPOSER_FLAGS -vv
        - travis_retry composer require --update-with-dependencies --prefer-dist --prefer-stable --no-progress --no-interaction --no-suggest friendsofphp/php-cs-fixer:^2.5
      script: vendor/bin/php-cs-fixer fix --dry-run -vv
    - stage: static code analysis
      php: 7.1
      env: COMPOSER_FLAGS=""
      install:
        - travis_retry composer update --optimize-autoloader --prefer-dist --prefer-stable --no-progress --no-interaction --no-suggest --no-dev $COMPOSER_FLAGS -vv
        - travis_retry composer require --update-with-dependencies --prefer-dist --prefer-stable --no-progress --no-interaction --no-suggest phpstan/phpstan:0.8.4
      script: vendor/bin/phpstan analyse -l 7 -c phpstan.neon --autoload-file=vendor/autoload.php --memory-limit=768M --no-progress src tests

notifications:
  email: false
