language: php
sudo: false
dist: trusty

php:
  - 7.1
  - 7.2

os: linux

env:
  - COMPOSER_FLAGS="--prefer-lowest"
  - COMPOSER_FLAGS=""

cache:
  directories:
    - $HOME/.composer/cache

addons:
  code_climate:
    repo_token: 43db4d76514521ffd97e65f2a6806a106ae168f1db55397741485212f9c70ae7

before_install:
  - phpenv config-rm xdebug.ini || echo "xdebug not available"
  - echo 'opcache.enable=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo 'opcache.enable_cli=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - travis_retry composer self-update

install:
  - travis_retry composer update --optimize-autoloader --prefer-dist --prefer-stable --no-progress --no-interaction --no-suggest --no-dev $COMPOSER_FLAGS -vv
  - travis_retry composer require --update-with-dependencies --optimize-autoloader --prefer-dist --prefer-stable --no-progress --no-interaction --no-suggest --dev $COMPOSER_FLAGS -vv symfony/cache
#  - travis_retry composer require --update-with-dependencies --optimize-autoloader --prefer-dist --prefer-stable --no-progress --no-interaction --no-suggest $COMPOSER_FLAGS --dev -vv phpunit/phpunit
#  - travis_retry composer require --update-with-dependencies --optimize-autoloader --prefer-dist --prefer-stable --no-progress --no-interaction --no-suggest $COMPOSER_FLAGS --dev -vv scriptfusion/phpunit-immediate-exception-printer:^1.3

script:
  - composer validate
#  - vendor/bin/phpunit --printer 'ScriptFUSION\PHPUnitImmediateExceptionPrinter\ImmediateExceptionPrinter' --colors --no-coverage
  - wget https://phar.phpunit.de/phpunit-6.4.3.phar && php phpunit-6.4.3.phar --colors --no-coverage

jobs:
  allow_failures:
    - php: nightly
  include:
    - php: nightly
      env: COMPOSER_FLAGS="--ignore-platform-reqs"
    - stage: test with coverage
      php: 7.1
      env:
        - COVERAGE=yes
        - COMPOSER_FLAGS=""
      before_install:
        - echo 'opcache.enable=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
        - echo 'opcache.enable_cli=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
        - travis_retry composer self-update
      script: wget https://phar.phpunit.de/phpunit-6.4.3.phar && php phpunit-6.4.3.phar --colors --coverage-clover=clover.xml --coverage-text
      after_success:
        - wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar && php -n coveralls.phar --verbose --coverage_clover=clover.xml
        - bash <(curl -s https://codecov.io/bash) -f clover.xml -F phpunit
    - stage: check coding style
      php: 7.1
      env: 
        - COMPOSER_FLAGS=""
        - TEST=phpcs
      script: wget https://github.com/squizlabs/PHP_CodeSniffer/releases/download/3.1.1/phpcs.phar && php phpcs.phar --colors
    - stage: check coding style
      php: 7.1
      env:
        - COMPOSER_FLAGS=""
        - TEST=php-cs-fixer
      script: wget https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/download/v2.7.1/php-cs-fixer.phar && php php-cs-fixer.phar fix --dry-run -vv
    - stage: static code analysis
      php: 7.1
      env:
        - COMPOSER_FLAGS=""
        - TEST=phpstan
#      script: wget https://github.com/phpstan/phpstan/releases/download/0.8.5/phpstan.phar && php phpstan.phar analyse -l 7 -c phpstan.neon --autoload-file=vendor/autoload.php --memory-limit=768M --no-progress src tests
      install:
        - travis_retry composer update --optimize-autoloader --prefer-dist --prefer-stable --no-progress --no-interaction --no-suggest --no-dev $COMPOSER_FLAGS -vv
        - travis_retry composer require --update-with-dependencies --optimize-autoloader --prefer-dist --prefer-stable --no-progress --no-interaction --no-suggest --dev $COMPOSER_FLAGS -vv phpstan/phpstan
      script: vendor/bin/phpstan analyse -l 7 -c phpstan.neon --autoload-file=vendor/autoload.php --memory-limit=768M --no-progress src tests

notifications:
  email: false
