language: php
sudo: false

php:
  - 5.6
  - 7.0
  - 7.1
  - nightly

os:
  - linux

env:
  - PREFER_LOWEST="--prefer-lowest"
  - PREFER_LOWEST=""

matrix:
  allow_failures:
  # fails due a segmentation fault
    - php: nightly
    - env: PREFER_LOWEST="--prefer-lowest"

before_script:
  - echo 'opcache.enable=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo 'opcache.enable_cli=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - travis_retry composer self-update
  - travis_retry composer update --optimize-autoloader --prefer-dist --prefer-stable --no-progress --no-interaction $PREFER_LOWEST

script:
  - vendor/bin/phpunit -c phpunit.library.xml --exclude-group useragenttest --colors=auto --coverage-text --coverage-clover=coverage.clover
#  - vendor/bin/phpcs --standard=psr2 -np src tests
#  - vendor/bin/php-cs-fixer fix --dry-run -vv

after_success:
#  - if [ "`phpenv version-name`" == "5.6" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
#  - if [ "`phpenv version-name`" == "5.6" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi

  - if [ "`phpenv version-name`" == "5.6" ]; then wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar; fi
  - if [ "`phpenv version-name`" == "5.6" ]; then php coveralls.phar --verbose --coverage_clover=coverage.clover; fi

notifications:
  email: false
