language: php
sudo: false

php:
  - 7.0
  - 7.1
  - nightly

os:
  - linux

env:
  - PREFER_LOWEST="--prefer-lowest"
  - PREFER_LOWEST=""

matrix:
  allow_failures:
    - php: nightly

before_install:
  - echo 'opcache.enable=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo 'opcache.enable_cli=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - travis_retry composer self-update

install:
  - travis_retry composer update --optimize-autoloader --prefer-dist --prefer-stable --no-progress --no-interaction $PREFER_LOWEST

script:
  - vendor/bin/phpunit --colors=auto --coverage-clover=coverage.clover
  - php -n -d memory_limit=768M vendor/bin/phpcs
  - php -n -d memory_limit=768M vendor/bin/php-cs-fixer fix --dry-run -vv

after_success:
  - wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
  - php -n coveralls.phar --verbose --coverage_clover=coverage.clover

notifications:
  email: false
