# https://dependabot.com/docs/config-file/

version: 1

update_configs:
  - default_assignees:
      - "mimmi20"
    default_reviewers:
      - "mimmi20"
    directory: "/"
    package_manager: "php:composer"
    update_schedule: "live"
    version_requirement_updates: "increase_versions"
    commit_message:
      prefix: "Build"
      include_scope: true
    ignored_updates:
      - match:
          dependency_name: "phpunit/phpunit"
