name: "Lint GitHub Actions workflows"

on:
  pull_request:
    paths:
      - ".github/**"

permissions:
  contents: read

jobs:
  actionlint:
    uses: "mimmi20/ci/.github/workflows/lint-actions.yml@master"
    with:
      skip-nasm-install: false
      skip-libimagequant-install: false

  # This is a meta job to avoid to have to constantly change the protection rules
  # whenever we touch the matrix.
  lint-status:
    name: "Lint Status"

    runs-on: "ubuntu-latest"

    if: always()

    needs: "actionlint"

    steps:
      - name: Failing run
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1

      - name: Successful run
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: exit 0
