# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

# file-version: 1.0

name: "Lock closed issue"

on:
  issues:
    types:
      - "closed"

jobs:
  lock:
    runs-on: "ubuntu-24.04"
    steps:
      - uses: "Dunning-Kruger/lock-issues@v1.1"
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
